import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createInterface } from "node:readline/promises";
import {
  availableModules,
  resolveEnabledModules,
  type ModuleManifestEntry,
} from "./modules-cli.ts";

const CONFIG_FILENAME = "nativescope.config.js";

/**
 * Gera o config a partir dos templates do manifesto: módulo ligado vira uma
 * linha ativa; desligado vira a mesma linha comentada (fica óbvio como ligar).
 */
function renderConfig(enabledKeys: Set<string>): string {
  const lines = availableModules().map((mod) =>
    enabledKeys.has(mod.key) ? `    ${mod.configTemplate}` : `    // ${mod.configTemplate}`,
  );
  return `// NativeScope configuration.
// Generated by \`nativescope init\`. Every module is opt-in — enable only what
// you want. Uncomment a line below (or re-run init) to turn a module on.
/** @type {import('react-native-nativescope/app').NativeScopeConfig} */
module.exports = {
  modules: {
${lines.join("\n")}
  },
};
`;
}

async function promptModules(modules: ModuleManifestEntry[]): Promise<Set<string>> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const enabled = new Set<string>();
  try {
    console.log("");
    console.log("Which modules do you want to enable? (Enter accepts the default)");
    console.log("");
    for (const mod of modules) {
      const isDefault = mod.key === "storage";
      const hint = isDefault ? "Y/n" : "y/N";
      const answer = (await rl.question(`  Enable ${mod.label} — ${mod.description}? [${hint}] `))
        .trim()
        .toLowerCase();
      const on = answer === "" ? isDefault : answer === "y" || answer === "yes";
      if (on) enabled.add(mod.key);
    }
  } finally {
    rl.close();
  }
  return enabled;
}

/**
 * `nativescope init`: escreve um nativescope.config.js escolhendo quais módulos
 * ligar. Interativo num TTY; com --yes ou sem TTY (CI), gera o default sensato
 * (storage ligado). Nunca sobrescreve um config existente sem --force.
 */
export async function runInit(
  projectDir: string,
  opts: { force: boolean; yes: boolean },
): Promise<void> {
  const existing = resolveEnabledModules(projectDir).configPath;
  if (existing && !opts.force) {
    console.log("");
    console.log(`A NativeScope config already exists: ${existing}`);
    console.log("Edit it directly, or re-run with --force to overwrite.");
    return;
  }

  const modules = availableModules();
  const interactive = Boolean(process.stdin.isTTY) && !opts.yes;
  const enabledKeys = interactive
    ? await promptModules(modules)
    : new Set(modules.filter((m) => m.key === "storage").map((m) => m.key));

  writeFileSync(join(projectDir, CONFIG_FILENAME), renderConfig(enabledKeys));

  console.log("");
  console.log(`Wrote ${CONFIG_FILENAME}`);
  const on = modules.filter((m) => enabledKeys.has(m.key));
  if (on.length > 0) {
    console.log("Enabled:");
    for (const m of on) console.log(`  ✓ ${m.label}`);
  } else {
    console.log("No modules enabled yet — edit the file to turn some on.");
  }
  console.log("");
  console.log("Next: run `npx nativescope` and open your app.");
}
